name: Build
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "*.md"

  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "*.md"

  workflow_dispatch:
    inputs:
      env:
        description: "GitHub Environment to use (secrets/vars)"
        type: choice
        required: true
        default: dev
        options:
          - dev
          - stage
          - prod
      project:
        description: "Playwright project to run"
        type: choice
        required: true
        default: login
        options:
          - registration
          - login
          - startpage
          - cookie-manager
          - instawp-setup
          # Still not working due to adsimple ID setup
          # - instawp-cookie-manager
      spec:
        description: "Optional spec path under tests/ (e.g. tests/wordpress/login.spec.ts)"
        required: false
        type: string
      grep:
        description: "Optional title filter passed as -g"
        required: false
        type: string
      headed:
        description: "Run in headed mode"
        required: false
        default: false
        type: boolean
      capture_media:
        description: "Capture screenshots/videos (CAPTURE_MEDIA)"
        required: false
        default: true
        type: boolean
      click_effects:
        description: "Enable click effects overlay (CLICK_EFFECTS)"
        required: false
        default: true
        type: boolean
      click_effects_slowmo_ms:
        description: "Ripple slowMo delay in ms (CLICK_EFFECTS_SLOWMO_MS)"
        required: false
        type: string


jobs:
  prebuild:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cfg:
          - data: [18, 20, 22]
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        env:
          CFG: ${{ toJSON(matrix.cfg) }}
        run: jq -r -n 'env.CFG | fromjson | @json "matrix=\(.data)"' >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: [prebuild]

    strategy:
      matrix:
        node-version: ${{ fromJson(needs.prebuild.outputs.matrix) }}

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'

    - name: Build
      run: |
        npm ci
        npm run build
