name: Publish package to NPMJS
on:
  release:
    types: [published]
  workflow_run:
      workflows: [CI]
      types:
        - completed
jobs:
  deploy_to_npm:
    if: github.event_name == 'release' && github.repository_owner == 'tonidy'
    runs-on: ubuntu-latest
    steps:
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:    
          name: plugin-artifact
          run_id: ${{ github.event.workflow_run.id }}

      - run: npm publish leapp-ec2*.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}