name: Deploy
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'

    - name: Build
      run: |
        npm ci
        npm run build

    - name: Pack
      run: |
        cd leapp-ec2-instance-connect-plugin
        npm pack

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: plugin-artifact
        path: leapp-ec2-instance-connect-plugin/*.tgz
        retention-days: 1

  deploy_to_npm:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org/'

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:    
          name: plugin-artifact

      - name: Push to NPM
        run: npm publish --access public leapp-ec2*.tgz

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          token: ${{ secrets.NPM_TOKEN }}
