name: Deploy
on:
  tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'

    - name: Build
      run: |
        npm ci
        npm run build

    - name: Pack
      if: |
        github.event_name == 'release' &&
        startsWith(github.ref, 'refs/tags/v')
      run: |
        cd leapp-ec2-instance-connect-plugin
        npm pack

    - name: Upload artifact
      if: |
        github.event_name == 'release' &&
        startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-artifact@v3
      with:
        name: plugin-artifact
        path: leapp-ec2-instance-connect-plugin/*.tgz
        retention-days: 1

  deploy_to_npm:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org/'

      - name: Download artifact
        if: |
          github.event_name == 'release' &&
          startsWith(github.ref, 'refs/tags/v')
        uses: actions/download-artifact@v3
        with:    
          name: plugin-artifact

      - name: Push to NPM
        if: |
          github.event_name == 'release' &&
          startsWith(github.ref, 'refs/tags/v')
          
        run: npm publish --access public leapp-ec2*.tgz

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          token: ${{ secrets.NPM_TOKEN }}
