name: Version Increment

on:
  push:
    branches: [ "main" ]

jobs:
  versions:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - run: npm version patch -m "[RELEASE] %s"

      - uses: stefanzweifel/git-auto-commit-action@v5
